image: rust:latest

stages: [lint, build, publish]

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends
    clang
    llvm-dev
    libclang-dev
    pkg-config
    build-essential
  - rm -rf /var/lib/apt/lists/*
  - rustup component add rustfmt clippy
  # Set the LIBCLANG_PATH environment variable
  - export LIBCLANG_PATH=/usr/lib/llvm-14/lib  # adjust version as needed

fmt:
  stage: lint
  script:
    - cargo fmt --all -- --check

clippy:
  stage: lint
  script:
    - cargo clippy --all-targets --all-features -D warnings

build:
  stage: build
  script:
    - cargo build

publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - when: never
  script:
    - cargo publish --locked