[package]
name = "nvme-telem"
version = "0.1.1"
edition = "2021"          
license = "MIT"
description = "NVMe SMART / telemetry collection for Linux"
repository = "https://gitlab.com/avakianssion/nvme-telem"
readme = "README.md"
keywords = ["nvme", "storage", "telemetry", "smart", "monitoring"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
nvme-cli-sys = "0.1.5"
